policies:
  - name: KerasPolicy
    epochs: 100
    batch_size: 50
    max_history: 2
    featurizer:
      - name: FullDialogueTrackerFeaturizer
        state_featurizer:
        - name: LabelTokenizerSingleStateFeaturizer
  - name: FallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: 'utter_fallback'
  - name: MemoizationPolicy
    max_history: 2
  - name: FormPolicy
